# Generated by Django 3.1.7 on 2021-03-23 20:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='published_date',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=blog.models.MinMaxFloat(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('szt.', 'szt.'), ('ml', 'ml'), ('l', 'l'), ('g', 'g'), ('dag', 'dag'), ('kg', 'kg')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=50),
        ),
    ]
