# Generated by Django 3.1.7 on 2021-03-24 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210323_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
