# Generated by Django 3.1.7 on 2021-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dish_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='kind_of_meal',
            field=models.CharField(choices=[('I śniadanie', 'I śniadanie'), ('II śniadanie', 'II śniadanie'), ('obiad', 'obiad'), ('deser', 'deser'), ('kolacja', 'kolacja'), ('przekąska', 'przekąska')], default=None, max_length=30, null=True),
        ),
    ]
