# Generated by Django 3.1.7 on 2021-03-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210327_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='country',
            field=models.CharField(choices=[('Grecja', 'Grecja'), ('Hiszpania', 'Hiszpania'), ('Indie', 'Indie'), ('Portugalia', 'Portugalia')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='kind_of_meal',
            field=models.CharField(choices=[('I śniadanie', 'I śniadanie'), ('II śniadanie', 'II śniadanie'), ('obiad', 'obiad'), ('deser', 'deser'), ('kolacja', 'kolacja'), ('przekąska', 'przekąska'), ('próba', 'próba')], default=None, max_length=30, null=True),
        ),
    ]
