# Generated by Django 3.1.7 on 2021-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210331_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='kind_of_meal',
            field=models.CharField(choices=[('I śniadanie', 'I śniadanie'), ('II śniadanie', 'II śniadanie'), ('obiad', 'obiad'), ('deser', 'deser'), ('kolacja', 'kolacja'), ('przekąska', 'przekąska')], default=None, max_length=30, null=True),
        ),
    ]
