# Generated by Django 3.1.7 on 2021-04-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210401_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='country',
            field=models.CharField(choices=[('Chiny', 'Chiny'), ('Grecja', 'Grecja'), ('Hiszpania', 'Hiszpania'), ('Indie', 'Indie'), ('Portugalia', 'Portugalia'), ('Tajlandia', 'Tajlandia')], default=None, max_length=30, null=True),
        ),
    ]
