# Generated by Django 3.1.7 on 2021-05-04 18:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210408_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=blog.models.MinMaxFloat(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('', ''), ('szt.', 'szt.'), ('ml', 'ml'), ('l', 'l'), ('g', 'g'), ('dag', 'dag'), ('kg', 'kg')], default=None, max_length=30),
        ),
    ]
