# Generated by Django 3.1.7 on 2021-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210504_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='country',
            field=models.CharField(choices=[('Chiny', 'Chiny'), ('Grecja', 'Grecja'), ('Hiszpania', 'Hiszpania'), ('Indie', 'Indie'), ('Portugalia', 'Portugalia'), ('Tajlandia', 'Tajlandia')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='kind_of_meal',
            field=models.CharField(choices=[('I śniadanie', 'I śniadanie'), ('II śniadanie', 'II śniadanie'), ('obiad', 'obiad'), ('deser', 'deser'), ('kolacja', 'kolacja'), ('przekąska', 'przekąska')], default=None, max_length=30),
        ),
    ]
