# Generated by Django 3.1.13 on 2021-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_dish_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='country',
            field=models.CharField(choices=[('Francja', 'Francja'), ('Gruzja', 'Gruzja'), ('Grecja', 'Grecja'), ('Hiszpania', 'Hiszpania'), ('Indie', 'Indie'), ('Tajlandia', 'Tajlandia'), ('INNE', 'INNE')], default=None, max_length=30),
        ),
    ]
