# Generated by Django 3.1.13 on 2021-12-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211108_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='diet',
            new_name='low_calories',
        ),
    ]
